import { Candidate } from "../types";

export const CANDIDATES: { dem: Candidate[]; rep: Candidate[] } = {
  dem: [
    {
      id: "bottoms",
      name: "Keisha Lance Bottoms",
      initials: "KB",
      photo: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Keisha_Lance_Bottoms.jpg",
      wiki: "Keisha_Lance_Bottoms",
      title: "Former Mayor of Atlanta · Former White House Senior Adviser",
      badges: [{ label: "Front-Runner", type: "frontrunner" }],
      background: "Attorney, judge, and Atlanta mayor (2018–2022). Served as Senior Adviser in the Biden White House. First elected to Atlanta City Council before becoming mayor.",
      platform: ["Expand Medicaid", "Tax relief for teachers", "Free community college", "Small business support", "Counter D.C. chaos"],
      funding: "~$1.1M raised (mid-2025) · Donor-funded",
      fundingPct: 55,
      poll: 40,
      pollNote: "AJC poll — leads Democratic field by ~29 pts",
    },
    {
      id: "duncan",
      name: "Geoff Duncan",
      initials: "GD",
      photo: null,
      wiki: "Geoff_Duncan",
      title: "Former Lt. Governor of Georgia (R→D)",
      badges: [{ label: "Party Switcher", type: "crossover" }],
      background: "Former Republican Lt. Governor (2019–2023), pro baseball player, business owner, and healthcare CEO. Switched to Democratic Party in August 2025 citing moral convictions.",
      platform: ["Bipartisan coalition", "Lower childcare costs", "Healthcare affordability", "Housing costs", "Reject extremism"],
      funding: "$1.1M+ raised (Jan. 2026) · Outside dark money groups backing him",
      fundingPct: 55,
      poll: 5,
      pollNote: "AJC poll — argues crossover appeal wins general",
    },
    {
      id: "thurmond",
      name: "Michael Thurmond",
      initials: "MT",
      photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Michael_Thurmond.jpg/120px-Michael_Thurmond.jpg",
      wiki: "Michael_Thurmond_(politician)",
      title: "Former DeKalb County CEO · Former State Labor Commissioner",
      badges: [],
      background: "Extensive public service: state representative, Labor Commissioner (won statewide twice), DeKalb County CEO, and interim school superintendent. Historian and attorney.",
      platform: ["Working families", "Healthcare access", "Education pathways", "Bridge racial/political divides", "Affordability"],
      funding: "$700K cash on hand (Jan. 2026) · Donor-funded",
      fundingPct: 35,
      poll: 11,
      pollNote: "AJC poll — 2nd place, running on experience",
    },
    {
      id: "esteves",
      name: "Jason Esteves",
      initials: "JE",
      photo: null,
      wiki: "Jason_Esteves",
      title: "Former Georgia State Senator · Attorney · Former Teacher",
      badges: [],
      background: "Emory law grad, former middle school teacher, attorney at McKenna Long & Aldridge and VP at Equifax. Served on Atlanta Public Schools board and in the Georgia State Senate.",
      platform: ["Lower cost of living", "Healthcare expansion", "Small business investment", "Education funding", "Repeal abortion ban"],
      funding: "~$1.1M raised (mid-2025) · Donor-funded",
      fundingPct: 55,
      poll: 3,
      pollNote: "AJC poll — endorsed by Jason Carter",
    },
    {
      id: "djackson",
      name: "Derrick Jackson",
      initials: "DJ",
      photo: null,
      wiki: "Derrick_Jackson_(politician)",
      title: "Georgia State Representative · Retired Navy Officer",
      badges: [],
      background: "State representative (2017–present), retired Navy officer, and former marketing manager. Ran for Lt. Governor in 2022. Focuses on working- and middle-class families.",
      platform: ["Working families", "Middle-class empowerment", "Veterans issues"],
      funding: "Limited public data available · Grassroots campaign",
      fundingPct: 10,
      poll: null,
      pollNote: "Not yet in major polls",
    },
    {
      id: "brown",
      name: "Olu Brown",
      initials: "OB",
      photo: "https://images.squarespace-cdn.com/content/v1/6086e453cab48b69b53d41fc/1621019539209-WZ7QU5966BTHPYSNEUY6/Olu+Brown-Color+Casual+2021+CURRENT.jpg?format=2500w",
      wiki: null,
      title: "Pastor · Community Leader",
      badges: [],
      background: "Faith leader and community organizer. Entered the Democratic primary as a grassroots candidate representing progressive and community-centered values.",
      platform: ["Community empowerment", "Faith-based values", "Grassroots governance"],
      funding: "Limited public data available · Grassroots campaign",
      fundingPct: 8,
      poll: null,
      pollNote: "Not yet in major polls",
    },
    {
      id: "duffy",
      name: "Amanda Duffy",
      initials: "AD",
      photo: null,
      wiki: null,
      title: "Accountant · Columbia County",
      badges: [],
      background: "Accountant from Columbia County. No prior political office. Her campaign website was unavailable at time of qualifying. Very limited public profile — one of the lower-tier entrants in the Democratic field.",
      platform: ["Limited public data available"],
      funding: "Limited public data available · Grassroots campaign",
      fundingPct: 5,
      poll: null,
      pollNote: "Not in major polls",
    },
  ],
  rep: [
    {
      id: "jones",
      name: "Burt Jones",
      initials: "BJ",
      photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqgDYBI3VB1qP2XhOJpw0WM04qxPIE7DeMU3q8cYvFWao7lDeI8ayqFCCMo2PLt8Iw6FsSId3d061TOMQh_sAzo4SFahTUZPwwlIIN2RYk&s=10",
      wiki: "Burt_Jones_(politician)",
      title: "Lieutenant Governor of Georgia (Incumbent)",
      badges: [
        { label: "Trump Endorsed", type: "trump" },
        { label: "Front-Runner", type: "frontrunner" },
      ],
      background: "Incumbent Lt. Governor and former state senator. Family made fortune in gas stations. Backed Trump's 2020 election challenges. Received Trump endorsement Aug. 2025. Leadership committee fundraising advantage now court-ordered frozen.",
      platform: ["Tax cuts", "Education reform", "Trump agenda", "Election integrity"],
      funding: "$10M+ via leadership committee (now court-frozen) · Unlimited fundraising advantage challenged by rivals",
      fundingPct: 100,
      poll: 22,
      pollNote: "Cygnal poll — polls vary widely: Jones 17–22%, Jackson 24–33%",
    },
    {
      id: "rjackson",
      name: "Rick Jackson",
      initials: "RJ",
      photo: null,
      wiki: "Rick_Jackson_(businessman)",
      title: "Founder & CEO, Jackson Healthcare",
      badges: [{ label: "Self-Funded $50M+", type: "selfmade" }],
      background: "Billionaire founder of Jackson Healthcare. Entered race Feb. 2026, immediately shaking up the field. No prior political experience. Sued Jones over campaign finance laws and won.",
      platform: ["Business experience", "Income tax cut", "Break up 'establishment cartel'", "Affordability"],
      funding: "$50M+ personal war chest · $40M+ pledged for advertising alone · Self-funded",
      fundingPct: 100,
      poll: 33,
      pollNote: "Quantus Insights poll — leads GOP field in recent surveys",
    },
    {
      id: "raffensperger",
      name: "Brad Raffensperger",
      initials: "BR",
      photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSho3pW00FHaSrrua0PO5GqQdKPRPdSQcDRS7swWv3kGmUkbrIQ0Jitk6d_rbWUm__wsSYt-GUKMWbw8_JfVung_9MZrddxaYAMRGso61mInQ&s=10",
      wiki: "Brad_Raffensperger",
      title: "Secretary of State of Georgia (Incumbent)",
      badges: [],
      background: "Incumbent Secretary of State who refused Trump's pressure to overturn Georgia's 2020 results. Engineer and businessman before politics. Largest donor-funded war chest in the GOP field.",
      platform: ["Jobs creation", "Lower taxes", "Conservative record", "Election integrity"],
      funding: "$5.4M cash on hand (Jan. 31, 2026) · Donor-funded · Capped at $8,400/donor",
      fundingPct: 75,
      poll: 10,
      pollNote: "Cygnal poll — 3rd; 2020 stance a liability with MAGA base",
    },
    {
      id: "carr",
      name: "Chris Carr",
      initials: "CC",
      photo: null,
      wiki: "Chris_Carr_(politician)",
      title: "Attorney General of Georgia (Incumbent)",
      badges: [],
      background: "UGA law grad and incumbent AG since 2016. Closely aligned with Gov. Brian Kemp's legacy. Did not back Trump's 2020 lawsuits but now pivoting aggressively toward MAGA voters.",
      platform: ["Affordability", "Public safety", "Kemp legacy", "Conservative governance"],
      funding: "$3.2M cash on hand (Jan. 31, 2026) · Donor-funded · Capped at $8,400/donor",
      fundingPct: 60,
      poll: 7,
      pollNote: "Cygnal poll — 4th; MAGA pivot underway",
    },
    {
      id: "kirkpatrick",
      name: "Gregg Kirkpatrick",
      initials: "GK",
      photo: "https://s3.amazonaws.com/ballotpedia-api4/files/thumbs/200/300/Gregg_Kirkpatrick_2026.jpg",
      wiki: null,
      title: "Executive · Manufacturing & Medical Devices",
      badges: [],
      background: "Longtime executive in steel manufacturing, military communications, and medical devices. Calls himself an 'authentic constitutional republican.' Has authored a 90+ page governing plan.",
      platform: ["Zero state income tax", "Property tax relief", "Trade school pipeline", "Anti-corruption dept.", "Election integrity"],
      funding: "Limited public data · Grassroots campaign",
      fundingPct: 8,
      poll: 1,
      pollNote: "co/efficient poll — lower-tier candidate",
    },
    {
      id: "dean",
      name: "Clark Dean",
      initials: "CD",
      photo: "https://cloudfront-us-east-1.images.arcpublishing.com/ajc/MLDITA7BPZDIZIKJ3JGKY6VXOA.png",
      wiki: null,
      title: "Republican Candidate",
      badges: [],
      background: "Republican candidate with limited public profile. Among the lower-tier candidates in the GOP primary field.",
      platform: ["Conservative values", "Limited government"],
      funding: "Limited public data · Grassroots campaign",
      fundingPct: 5,
      poll: 1,
      pollNote: "co/efficient poll",
    },
    {
      id: "olinger",
      name: "Leland Olinger II",
      initials: "LO",
      photo: "https://images.ivoterguide.com/candidates/065357.jpg",
      wiki: null,
      title: "Former State Senate Candidate · Advocate",
      badges: [],
      background: "Former state senate candidate and advocate focused on family law reform and mental health solutions.",
      platform: ["Family law reform", "Mental health solutions", "Conservative values"],
      funding: "Limited public data · Grassroots campaign",
      fundingPct: 5,
      poll: null,
      pollNote: "Not yet in major polls",
    },
    {
      id: "yasger",
      name: "Ken Yasger",
      initials: "KY",
      photo: "https://assets.civicengine.com/uploads/candidate/headshot/649737/649737.jpg",
      wiki: null,
      title: "Republican Candidate",
      badges: [],
      background: "Republican candidate with limited public profile. Among the lower-tier candidates in the GOP primary field.",
      platform: ["Conservative values", "Limited government"],
      funding: "Limited public data · Grassroots campaign",
      fundingPct: 5,
      poll: null,
      pollNote: "Not yet in major polls",
    },
    {
      id: "twilliams",
      name: "Thomas Williams",
      initials: "TW",
      photo: "https://ximage.c-spanvideo.org/eyJidWNrZXQiOiJwaWN0dXJlcy5jLXNwYW52aWRlby5vcmciLCJrZXkiOiJGaWxlc1wvYTRhXC8yMDIyMDUwMTE5MDIzODAwMV9oZC5qcGciLCJlZGl0cyI6eyJleHRyYWN0Ijp7ImxlZnQiOjY5MiwidG9wIjowLCJ3aWR0aCI6NDYxLCJoZWlnaHQiOjU5MH0sInJlc2l6ZSI6eyJmaXQiOiJjb3ZlciIsImhlaWdodCI6MjAwLCJ3aWR0aCI6MjAwfX19",
      wiki: null,
      title: "Retired · Software Engineer & Electronics · Wilkinson County",
      badges: [],
      background: "Retired after 35 years at Robins Air Force Base in software engineering and electronics. UGA business graduate. Previously ran for governor in the 2022 Republican primary, losing to Brian Kemp. This is his second run for the office.",
      platform: ["Election integrity", "Oppose vaccine mandates", "Women's sports protections", "Parental rights in education", "Fight Democratic economic policies"],
      funding: "Limited public data available · Grassroots campaign",
      fundingPct: 5,
      poll: null,
      pollNote: "Not in major polls",
    },
  ],
};